version: '3'
services:
  mysql:
    build:
      context: "./mysql"
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}:/app"
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build: 
      context: "./phpmyadmin"
    environment:
      - "PMA_ARBITRARY=1"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
volumes:
  phpmyadmin:
    driver: "${VOLUMES_DRIVER}"