#User defined
user:
  mysql_version:
    label:
      MySQL version
    hint:
      Select MySQL version
    type:
      select
    values:
      - 5.7
      - 8
    target:
      MYSQL_VERSION

  # customize_server_root_path:
  #   label:
  #     Server root
  #   type:
  #     input
  #   values:
  #     /var/www
  #   hint:
  #     Server document root
  #   target:
  #     SERVER_ROOT

#System defaults
system:
  # show_localpath_selector:
  #   true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      PMA_PORT
    others:
      - MYSQL_PORT


