name: MySql

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Mysql
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MYSQL_VERSION: "5.7"
    - name: Verify MySQL connection from host
      run:  docker-compose ps
    # - name: Enter the container
    #   run:  docker-compose exec mysql sh
    - name: Show Database
      run: |
        mysql -h127.0.0.1 -uroot -ppassword -e "SHOW DATABASES";
      # run: mysql -uroot -p{{env.DB_ROOT_PASSWORD}} -e 'SELECT version()'
      # run:  |
      #     sudo apt-get update && sudo apt-get install -y mysql-client
      #     mysql --host mysql_1 -uadmin -ppassword -e "SHOW DATABASES"

