name: MySql

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Mysql
      run: docker-compose -f "docker-compose.yml" up -d --build
      env:
        DB_ROOT_PASSWORD: password
        DB_PASSWORD: password
        DB_USER: admin
        DB_NAME:  test
        MYSQL_VERSION: "5.7"
    - name: Verify MySQL container
      run:  docker-compose ps
    - name: Verify MySQL running from host, create Database and show Database
      run: |
        sleep 30s
        docker exec mysql_mysql_1 ls -la /var/run/mysqld
    - name: Verify MySQL database from user
      run:  docker exec mysql_mysql_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec mysql_mysql_1 mysql -uroot -ppassword -e "CREATE DATABASE deck"
    - name: Verify Database create or not
      run:  docker exec mysql_mysql_1 mysql -uroot -ppassword -e "SHOW DATABASES"